#!/bin/bash

# 1x1
../scalerx -r 0 -k 12x12 $1-1.png $1-1x.png

# 2x2
../scalerx -k 2 $1-1.png $1-2.png
../scalerx -r 0 -k 6x6 $1-2.png $1-2x.png

# 3x3
../scalerx -k 3 $1-1.png $1-3.png
../scalerx -r 0 -k 4x4 $1-3.png $1-3x.png

# 4x4
../scalerx -k 4 $1-1.png $1-4.png
../scalerx -r 0 -k 3 $1-4.png $1-4x.png

# 2x3
../scalerx -k 2x3 $1-1.png $1-2x3.png
../scalerx -r 0 -k 6x4 $1-2x3.png $1-2x3x.png

# 2x4
../scalerx -k 2x4 $1-1.png $1-2x4.png
../scalerx -r 0 -k 6x3 $1-2x4.png $1-2x4x.png


